openapi: 3.0.0
info:
  title: Password Reset API
  version: 1.0.0
  description: API endpoints for password reset functionality

paths:
  /api/auth/forgot-password:
    post:
      summary: Request password reset
      description: |
        Request a password reset email for the given email address.
        Returns success regardless of whether email exists (prevents enumeration).
        Rate limited to 3 requests per 15 minutes per email.
      operationId: requestPasswordReset
      tags:
        - Password Reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: Email address to send reset link to
                  example: user@example.com
      responses:
        '200':
          description: Request accepted (always returned, regardless of email validity)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: If an account exists for that email, a password reset link has been sent
        '400':
          description: Invalid request (malformed email, missing fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Too many requests
                  message:
                    type: string
                    example: Please wait 5 minutes before requesting another reset
                  retryAfter:
                    type: integer
                    description: Seconds until next request allowed
                    example: 300

  /api/auth/reset-password:
    post:
      summary: Reset password with token
      description: |
        Reset user password using valid reset token.
        Token is single-use and expires after 1 hour.
      operationId: resetPassword
      tags:
        - Password Reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - newPassword
              properties:
                token:
                  type: string
                  description: Reset token from email link (64 hex characters)
                  pattern: '^[a-f0-9]{64}$'
                  example: a1b2c3d4e5f6...
                newPassword:
                  type: string
                  format: password
                  minLength: 8
                  description: New password (min 8 characters)
                  example: newSecurePassword123
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Password reset successful. You can now log in with your new password.
        '400':
          description: Invalid request (malformed token, weak password, missing fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid token
                  message:
                    type: string
                    example: This password reset link is invalid or has expired. Please request a new one.
        '409':
          description: Token already used
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Token already used
                  message:
                    type: string
                    example: This password reset link has already been used. Please request a new one.

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error type
          example: Validation error
        message:
          type: string
          description: Human-readable error message
          example: Invalid email address format
        fields:
          type: object
          description: Field-specific validation errors (optional)
          additionalProperties:
            type: string
          example:
            email: Must be a valid email address
            newPassword: Must be at least 8 characters

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: authjs.session-token
      description: NextAuth.js session cookie (not required for these endpoints)

security: []  # No authentication required for password reset endpoints

tags:
  - name: Password Reset
    description: Password reset functionality
